config/routes.rb
Rails.application.routes.draw do


  resources :qsearches

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users do
         get '/users/sign_out' => 'devise/sessions#destroy'
         match 'register' => 'users#create', :as => :register
  end


  resources :contacts
   root 'home#index'
   get '/about', :to => "home#about", as: :about
   get 'blog/index'
   get 'course/index'
   get 'course/show'
  resources :downloads,  only: [:index, :new, :create, :destroy]
  resources :questions,  only: [:index, :new, :create, :destroy]
  resources :searches
  resources :results
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact < ActiveRecord::Base
 # validates :number, :numericality => {:only_integer => true}
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :paper
  has_many :download
  has_many :question
end

app/models/download.rb
class Download < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader
    validates :course_id, presence: true
    validates :paper_id, presence: true
    validates :attachment, presence: true
end

app/models/paper.rb
class Paper < ActiveRecord::Base
  belongs_to :course
  has_many :download
  has_many :question
end

app/models/qsearch.rb
class Qsearch < ActiveRecord::Base

 def questions
			@questions ||= find_questions
	end

	private
		def find_questions
		  questions = Question.order(:question_paper)
		  questions = questions.where(paper_id: paper_id) if paper_id.present?
		  questions
		end
end

app/models/question.rb
class Question < ActiveRecord::Base
  mount_uploader :question_paper, QuestionPaperUploader
    validates :course_id, presence: true
    validates :paper_id, presence: true
    validates :question_paper, presence: true
#    has_many :course
#    has_many :paper
end

app/models/result.rb
class Result < ActiveRecord::Base
end

app/models/search.rb
class Search < ActiveRecord::Base


	def downloads
			@downloads ||= find_downloads
	end

	private
		def find_downloads
		  downloads = Download.order(:attachment)
		  downloads = downloads.where(paper_id: paper_id) if paper_id.present?
		  downloads
		end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  protected
	def confirmation_required?
		true
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/qsearches_helper.rb
module QsearchesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/confirmable/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_footer.html.erb
<div class="footer_bg"><!-- start footer -->
  <div class="container">
    <div class="row  footer">
      <div class="copy text-center">
        <p class="link">
          <span>&#169; All rights reserved | Design by&nbsp;<a href="http://sumasgroup.com/"> SumasGroup</a></span></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header_bg">
<div class="container">
	<div class="row header">
		<div class="logo navbar-left">
			<h1><a href="index.html">Sumas</a></h1>
		</div>
		<div class="h_search navbar-right">
			<form>
				<input type="text" class="text" value="Enter text here" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter text here';}">
				<input type="submit" value="search">
			</form>
		</div>
		<div class="clearfix"></div>
	</div>
</div>
</div>
<div class="container">
	<div class="row h_menu">
		<nav class="navbar navbar-default navbar-left" role="navigation">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		    </div>
		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">

<li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
 <li class="<%= 'active' if current_page?(course_index_path) %>"><%= link_to "Courses", course_index_path %></li>
<li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
<li class="<%= 'active' if current_page?(blog_index_path) %>"><%= link_to "Blog", blog_index_path %></li>
<li class="<%= 'active' if current_page?(new_contact_path) %>"><%= link_to "Contact", new_contact_path %></li>
<li class="<%= 'active' if current_page?(new_user_session_path) %>"><%= link_to "Students", new_user_session_path %></li>


		      </ul>
		    </div><!-- /.navbar-collapse -->
		    <!-- start soc_icons -->
		</nav>
		<div class="soc_icons navbar-right">
			<ul class="list-unstyled text-center">
				<li><a href="#"><i class="fa fa-twitter"></i></a></li>
				<li><a href="https://www.facebook.com/pages/Sumas/257339617723716"><i class="fa fa-facebook"></i></a></li>
				<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
				<li><a href="#"><i class="fa fa-youtube"></i></a></li>
				<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
			</ul>
		</div>
	</div>
</div>

app/views/layouts/_students_nav.html.erb
<div class="col-md-2" style="margin-left: 90px;">
    <nav class="navbar navbar-default" role="navigation">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse">
            <div class="panel-heading "> <span class="glyphicon glyphicon-star"></span>Student Panel</div>
            <ul class="nav nav-stacked">
<li class="<%= 'active' if current_page?( new_search_path) %>"><%= link_to "Assingments",  new_search_path %></li>
<li class="<%= 'active' if current_page?( new_search_path) %>"><%= link_to "Questions", new_qsearch_path %></li>

                <li><a href="#">Attendence</a></li>
              <li class="<%= 'active' if current_page?( results_path) %>"><%= link_to "Results", results_path %></li>
                <li><a href="#">Time Table</a></li>
            </ul>
        </div>
    </nav>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Sumas</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <script>
			$(function() {
				$('#da-slider').cslider ({
					autoplay : true,
					bgincrement : 450
                                        });
                                   });
		</script>

	       <script>
			$(document).ready(function(){
                                  $("#owl-demo").owlCarousel({
					items : 4,
					lazyLoad : true,
					autoPlay : true,
					navigation : true,
					navigationText : ["", ""],
					rewindNav : false,
					scrollPerPage : false,
					pagination : false,
					paginationNumbers : false
				});

			});
		</script>

<div class="navbar-text">
 <% if notice %>
  <div class="alert alert-success" role="alert"><%= notice %></div>
<% end %>
<% if alert %>
  <div class="alert alert-danger"><%= alert %></div>
<% end %>
</div>
</head>


<body>

<%= render :partial => "layouts/header" %>

<%= yield %>

<%= render :partial => "layouts/footer" %>

</body>

</html>