config/routes.rb
Rails.application.routes.draw do


  resources :qsearches

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users do
         get '/users/sign_out' => 'devise/sessions#destroy'
         match 'register' => 'users#create', :as => :register
  end


  resources :contacts
   root 'home#index'
   get '/about', :to => "home#about", as: :about
   get 'blog/index'
   get 'course/index'
   get 'course/show'
  resources :downloads,  only: [:index, :new, :create, :destroy]
  resources :questions,  only: [:index, :new, :create, :destroy]
  resources :searches
  resources :results
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact < ActiveRecord::Base
 # validates :number, :numericality => {:only_integer => true}
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :paper
  has_many :download
  has_many :question
end

app/models/download.rb
class Download < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader
    validates :course_id, presence: true
    validates :paper_id, presence: true
    validates :attachment, presence: true
end

app/models/paper.rb
class Paper < ActiveRecord::Base
  belongs_to :course
  has_many :download
  has_many :question
end

app/models/qsearch.rb
class Qsearch < ActiveRecord::Base

 def questions
			@questions ||= find_questions
	end

	private
		def find_questions
		  questions = Question.order(:question_paper)
		  questions = questions.where(paper_id: paper_id) if paper_id.present?
		  questions
		end
end

app/models/question.rb
class Question < ActiveRecord::Base
  mount_uploader :question_paper, QuestionPaperUploader
    validates :course_id, presence: true
    validates :paper_id, presence: true
    validates :question_paper, presence: true
#    has_many :course
#    has_many :paper
end

app/models/result.rb
class Result < ActiveRecord::Base
end

app/models/search.rb
class Search < ActiveRecord::Base


	def downloads
			@downloads ||= find_downloads
	end

	private
		def find_downloads
		  downloads = Download.order(:attachment)
		  downloads = downloads.where(paper_id: paper_id) if paper_id.present?
		  downloads
		end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  protected
	def confirmation_required?
		true
	end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/controllers/results_controller.rb
class ResultsController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/qsearches_helper.rb
module QsearchesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/results/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<%= render :partial => "layouts/students_nav" %>
<div style="margin-left: 290px;">

<h1>Listing results</h1>

 <ul>
    <li>
    <div><a target="_blank" href="https://studentservices.ignou.ac.in/TE_Result/termendjune14/TermEndJun14.asp">June 2014 Exam Result (New-I)</a></div>
    </li>
    <li>
    <div><a target="_blank" href="https://studentservices.ignou.ac.in/TE_Result/termendjune14/TermEndJun142.asp">June 2014 Exam Result (New-II)&nbsp;</a></div>
    </li>
    <li>
    <div><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/termenddec13/TermEndDec13_2.asp">December 2013 Exam Result -II&nbsp;</a></div>
    </li>
    <li>
    <div><a target="_blank" href="https://studentservices.ignou.ac.in/TE_Result/termenddec13/TermEndDec13.asp">December 2013 Exam Result -I&nbsp;</a></div>
    </li>
    <li>
    <div><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/TermEndOct13/TermEndOct13.asp">BHM, BAIHA &amp; MHA October 2013 </a></div>
    </li>
    <li>
    <div><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/BHMApril13/TEBhmapr13.asp">BHM, BAIHA &amp; MHA April 2013 </a></div>
    </li>
    <li>
    <div><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/termendjune13/TermEndjun13.asp">June 2013 Exam Result&nbsp;</a></div>
    </li>
    <li>
    <div><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/termenddec12/TermEndDec12.asp">December 2012 Exam Result</a></div>
    </li>
    <li>
    <div><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/TermEndOct12/TermEndOct12.asp">BHM, BAIHA &amp; MHA October 2012</a></div>
    </li>
    <li>
    <div><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/termendjun12/TermEndjun12.asp">June 2012 Exam Result&nbsp;</a></div>
    </li>
    <li>
    <div><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/BHMApril12/TEBhmapr12.asp">BHM/MHA/BAIHA Result 2012&nbsp;</a></div>
    </li>
    <li><span><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/TEFCED0612/TEfced0612.asp">FCED June 2012 Exam Result</a></span></li>
    <li><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/termenddec11/TermEndDec11.asp">Results December 2011&nbsp;</a>&nbsp; &nbsp;</li>
    <li><a target="_blank" href="https://studentservices.ignou.ac.in/TE_Result/termendjun11/TermEndjun11.asp">Results June 2011</a>&nbsp;</li>
    <li><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/BHMOct11/BHM1011.asp">BHM, BAIHA October-2011</a></li>
    <li><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/BHMApril11/TEBhmapr11.asp">BHM, BAIHA April-2011</a></li>
    <li><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/termenddec10/TermEndDec10.asp"><span>Results December 2010</span></a></li>
    <li><span><span><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/TermEndOct10/TermEndOct10.asp">BHM, BAIHA &amp; MHA October 2010</a></span></span></li>
    <li><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/TermEndJun10/TermEndJun10.asp">June 10 Exam Result</a></li>
    <li><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/BHMApril10/BHMApril10.asp">BHA, BAIHA, MHA April-10</a></li>
    <li><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/TermEnddec09/termenddec09.asp">December 09 Exam Result</a></li>
    <li><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/TermEndJun09/termendjun09.asp">June 09 Exam Result</a></li>
    <li><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/BHMOct09/BHMOct09.asp">BHA, MHA, BAIHA Oct-09</a></li>
    <li><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/BHMApril09/BHMApril09.asp">BHM, BAIHA April-09</a></li>
    <li><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/TermEndDec08/TermEndDec08.asp">Dec.08 Exam Result&nbsp;</a></li>
    <li><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/TermEndJun08/TermEndJun08s1.asp">June 08 (for MCA/BCA/MP)</a></li>
    <li><a target="_blank" href="http://studentservices.ignou.ac.in/TE_Result/TermEndJun08/TermEndJun08s2.asp">June 08 (for Others Programmes)</a></li>
</ul>


<%#= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>New result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @result.title %>
</p>

<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>